apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-service

  ports:
    - protocol: TCP
      port: 3000
      targetPort: {{ .Values.service.port }}

  # Export port to external network (e.g. for testing)
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000