# Data store
mongo:
  # Image and version number (macOS)
  #image:
  #  repository: mongo
  #  tag: "8.0"
  # Image and version number (pi)
  image:
    repository: apcheamitru/arm32v7-mongo
    tag: 3.2.20

  # Expose ports
  port: 27017
  database: tracker-testbed
  
  # Define storage size for the MongoDB data store
  storage:
    size: 5Gi
    
# Service (includes API)
service:
  replicaCount: 1
  image:
    repository: chrisah2/tracker-testbed-service
    tag: 0.4-armhf
    pullPolicy: Always

  # Expose ports
  port: 3000

  # Environment variables
  env:
    NODE_ENV: production
# End of file
